### PR TITLE
Fix Gemfile.lock

### PR DESCRIPTION
**Pull request by zysim**
Side effect from fixing #16. Our `Gemfile.lock` is apparently unparseable, so I've tried my best to recreate it from a new `Gemfile`, as I never committed the original one, because I thought. Naturally the original `Gemfile`'s since been lost to time, so I can only hope that it is similar, and that the resulting _pretty_ different lockfile is actually fine. I _have_ tried running it locally though, and everything's still in order, so this _should_ be fine.

### CODE REVIEW

**Comment by Nanoseb** [comment]
ok, great
when you wrote "I tried running it locally" you mean running jekyll? 
If that works and the resulting .html is the expected one, then I think it is safe to merge it.

**Comment by zysim** [comment]
> You mean running Jekyll

Yep. Ran `bundle exec jekyll serve`, scrolled through the whole page, and clicked every last button. Everything still works :+1: I'll go ahead and merge it then.

**Comment by Nanoseb** [comment]
yes, go ahead and discard my comment on the issue. 
Worst case scenario it doesn't work, but that's fine. It's not like this website is super critical, we can live with some downtime ;)

**Comment by zysim** [comment]
_Nonsense. This is the greatest site in the world._

**Pull request merged**
